# Site variables
title: STATUS:6
url: https://www.example.com

# Sass/SCSS
sass:
  style: :compressed

# GitHub Flavored Markdown is the default in Jekyll 4.0.0
kramdown:
  input: GFM
  hard_wrap: false
